services:
  fastapi-clip-service:
    image: fastapi-clip-service:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # 指定需要的 GPU 數量
              capabilities: [gpu]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"