services:
  fastapi-clip-service:
    image: fastapi-clip-service:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"